# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TestPods' do
    pod 'GinhoorFramework', :podspec => '../GinhoorFramework.podspec'  #指定podspec文件
end

target 'TestPodsTests' do

end

